print('Welcome to the Mad Lib Generator!')

adjective1 = raw_input('Type in an adjective: ')
adjective2 = raw_input('Type in another adjective: ')
adjective3 = raw_input('Type in a third adjective: ')
adjective4 = raw_input('And now one more adjective: ')
plural_animal = raw_input('Enter a plural animal, such as "wombats": ')
verb = raw_input('Enter a verb: ')
plural_noun = raw_input('Enter a plural noun: ')
woman_musician = raw_input('Type in the name of a female musician: ')
beverage = raw_input('Name a beverage: ')
body_part = raw_input('Name a body part: ')


print("")
print("Great choices! Here's your story:")
print("--------------------")
print("There once was a " + adjective1 + " programmer named " + woman_musician + " who wanted to build a " + adjective2 + " mobile app to help " + adjective3 + " " + plural_animal + " find new homes.")
print("")
print(woman_musician + " stayed up all night, drinking lots of caffeinated " + beverage + " as she worked and worked, trying to complete her " + adjective4 + " program.")
print("")
print("Whenever " + woman_musician + " hit a dead end, she would exclaim, *" + plural_noun + "*!")
print("")
print("But she was not discouraged, and after a quick break to " + verb + " and clear her head, she would get back to work.")
print("")
print("By morning, when the sun started to rise, she let out a big yawn, stretched her " + body_part + ", and got back to work.")
print("--------------------")
